### PR TITLE
[WIP] modify types for chat completion stream response

### PR DESCRIPTION
**Pull request by oslfmt**
Attempt to solve issue #75.

I've changed the following types to match the OpenAI API spec. Couple of questions:
- Which types do you determine to be "Option"? I've stripped the option type from any required types as specified by the API spec, but not sure if option should be applied to the other types or not
- I've noticed there's an enum type `ChatCompletionFunctionCall` and just a `FunctionCall` type. Not sure which I should use.

Beyond that, how do you go about updating the yaml file? As the one in the current repo is out of date. Should I pull the updated spec into this repo as well?

### CODE REVIEW

**Comment by 64bit** [comment]
Thank you @victor-wei126. 

> Which types do you determine to be "Option"? I've stripped the option type from any required types as specified by the API spec, but not sure if option should be applied to the other types or not
I determinte `Option` from the spec, the fields which are not in the `required` list are `Option`als. 

> I've noticed there's an enum type ChatCompletionFunctionCall and just a FunctionCall type. Not sure which I should use.
The best is to look at OpenAPI spec to determine which one (sometimes spec doesnt have details about streaming responses - then the best is to execute and see API response)

> Beyond that, how do you go about updating the yaml file? As the one in the current repo is out of date. Should I pull the updated spec into this repo as well?
My usual practice was to get upstream spec in my pull request AND the diff was what I used to update the rest of the code / types.rs

**Comment by victor-wei126** [comment]
@64bit Thanks for the response.

I've updated the types now to reflect what I think is proper (Option or not), trying to reflect the latest spec as closely as possible. The main question is whether to leave ID, object, and created types as option or not, as @lpi mentioned it is easier as openrouter.ai does not provide them.

> The best is to look at OpenAPI spec to determine which one
`FunctionCall` and `ChatCompletionFunctionCall` are types define in async-openai library, not the official specification itself. I choose to use `FunctionCall` type as this more closely resembles the official spec.

> My usual practice was to get upstream spec in my pull request AND the diff was what I used to update the rest of the code / types.rs
Perfect, I'll do this then. I'll also test against the API response as you mentioned above. If I have any questions, will let you know.

Just out of curiosity - is there any way to automatically test the types against the yaml spec? I read a bit about OpenAPI and saw they have some functionality regarding automatic code generation. Not entirely sure about it though - was wondering if you had used this feature so I can speed up the development here if possible.

**Comment by 64bit** [comment]
> By upstream spec do you mean the current spec in this repo or the latest openai-openapi spec?

I mean openai-openapi spec, the source of truth.

> Just out of curiosity - is there any way to automatically test the types against the yaml spec?

I shared my experience with auto generation in this comment https://github.com/64bit/async-openai/issues/85#issuecomment-1646752463 

I think for auto generation to be practical, there's a need for a good openapi spec to Rust generator, with ability to customize generated names. (There could be one - I haven't searched in a long time) 

But for now the best way to test is using examples. They serve two purposes: documentation for users and also testing when making changes.

**Comment by oslfmt** [comment]
@64bit this PR is ready for review

**Comment by 64bit** [comment]
Thanks!

I'll take a look, btw seems like your Github account changed?

**Review by 64bit — APPROVED** [review]

**Comment by 64bit** [comment]
This is released in v0.13.0

**Comment by oslfmt** [comment]
Yup haha changed my name but still me

**Pull request merged**
