### PR TITLE
do not print key in Debug

### PR DESCRIPTION
**Pull request by Emilgardis**

### CODE REVIEW

**Comment by 64bit** [comment]
Hi @Emilgardis Thank you for the PR! 

Actually `AzureConfig` suffers from the same security issue. Might as well fix both in one go?

**Comment by Emilgardis** [comment]
Done!

**Review by 64bit — APPROVED** [review]
Thank you!

**Comment by 64bit** [comment]
This is released in v0.14.3

**Comment by TmLev** [comment]
It also makes sense to use https://docs.rs/secrecy/latest/secrecy/

**Comment by 64bit** [comment]
Thanks @TmLev thats actually a good suggestion. 
I'm tracking it here https://github.com/64bit/async-openai/issues/113

**Pull request merged**
